"""
components/digital_twin.py
===========================
Digital Twin (3D Bin Packing Plan) component.

  - Displays the EXACT 3D Bin Packing figure generated by the Loading Planner
    (View 1) — the "Gold Standard" — by extracting it directly from session state.
  - No independent rendering: the worker panel is the single source of truth.
"""

import streamlit as st
from state.fleet_state import Fleet


def render_digital_twin(fleet: Fleet):
    """
    Render the Digital Twin 3D visualization of the optimal packing plan.

    This extracts the exact Plotly figure generated by the Loading Planner
    (View 1) and displays it — ensuring a pixel-identical view of the layout.

    Parameters
    ----------
    fleet : Fleet
        The fleet whose packing_layout metadata will be shown.
    """
    layout = fleet.packing_layout.get('layout', {})
    packed_items = layout.get('packed_items', [])

    st.subheader("Digital Twin — 3D Packing Plan (Gold Standard)")
    st.caption("Optimal layout generated by the Loading Planner (View 1)")

    # Summary metrics
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Fill Rate", f"{fleet.fill_percentage:.1f}%")
    with col2:
        st.metric("Packed Items", f"{len(packed_items)}")
    with col3:
        total_weight = sum(float(p.get('weight', 0)) for p in packed_items)
        st.metric("Total Weight", f"{total_weight:.0f} kg")
    with col4:
        unfitted = layout.get('unfitted_items', [])
        st.metric("Unfitted", f"{len(unfitted)}")

    # --- Extract and display the exact figure from the worker panel ---
    # Per-fleet lookup keyed by bin part number (matches
    # fleet.packing_layout['layout']['part_number'] set in
    # register_fleet_from_packing_result), so each fleet's twin shows its own
    # layout. Falls back to the latest rendered figure for compatibility.
    figures = st.session_state.get('fleet_3d_figures', {})
    part_no = layout.get('part_number', '')
    fig = figures.get(part_no) or st.session_state.get('last_3d_figure')

    if fig is not None:
        st.plotly_chart(
            fig,
            width='stretch',
            key=f"twin_3d_{fleet.id}",
        )
    else:
        st.info(
            "📦 No 3D packing layout has been generated yet. "
            "Switch to the Worker/Planner view, create a packing plan, "
            "and the layout will appear here automatically."
        )

    # Display packed item details
    if packed_items:
        with st.expander("Packed Items Details"):
            for item in packed_items:
                pos = [float(v) for v in item.get('position', [0, 0, 0])]
                dims = [float(v) for v in item.get('dimensions', [0, 0, 0])]
                st.markdown(
                    f"**{item['part_number']}** — "
                    f"Pos: ({pos[0]:.0f}, {pos[1]:.0f}, {pos[2]:.0f}) cm | "
                    f"Dims: ({dims[0]:.0f}, {dims[1]:.0f}, {dims[2]:.0f}) cm | "
                    f"Weight: {item.get('weight', 0):.0f} kg"
                )