"""
components/digital_twin.py
===========================
Digital Twin (3D Bin Packing Plan) component.

  - Displays the EXACT 3D Bin Packing figure generated by the Loading Planner
    (View 1) — the "Gold Standard" — by extracting it directly from session state.
  - No independent rendering: the worker panel is the single source of truth.
"""

import streamlit as st
from state.fleet_state import Fleet


def render_digital_twin(fleet: Fleet):
    """
    Render the full Digital Twin panel: summary metrics + 3D figure
    (body) followed by the Virtual Rear-CCTV "More" expander.
    """
    render_digital_twin_body(fleet)
    render_digital_twin_more(fleet)


def render_digital_twin_body(fleet: Fleet):
    """
    Render the Digital Twin body: divider, summary metrics and the 3D
    packing figure — everything that should align with the CCTV panel.
    """
    layout = fleet.packing_layout.get('layout', {})
    packed_items = layout.get('packed_items', [])

    st.markdown("---")

    # Summary metrics
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Fill Rate", f"{fleet.fill_percentage:.1f}%")
    with col2:
        st.metric("Packed Items", f"{len(packed_items)}")
    with col3:
        total_weight = sum(float(p.get('weight', 0)) for p in packed_items)
        st.metric("Total Weight", f"{total_weight:.0f} kg")
    with col4:
        unfitted = layout.get('unfitted_items', [])
        st.metric("Unfitted", f"{len(unfitted)}")

    # --- Extract and display the figure ---
    # Per-fleet lookup keyed by bin part number (matches
    # fleet.packing_layout['layout']['part_number']). Falls back to a
    # live rebuild from packed_items (Gold-Standard shared painter), so a
    # stale/missing cache can NEVER render an empty truck again. Final
    # fallback is the latest worker figure for backwards compatibility.
    figures = st.session_state.get('fleet_3d_figures', {})
    part_no = layout.get('part_number', '')
    fig = figures.get(part_no)
    if fig is None and packed_items:
        try:
            from services.twin_figure import build_twin_figure
            fig = build_twin_figure(
                packed_items,
                tuple(fleet.truck_dimensions),
                part_no,
            )
            if fig is not None and part_no:
                st.session_state.setdefault(
                    'fleet_3d_figures', {})[part_no] = fig
        except Exception:
            fig = None
    if fig is None:
        fig = st.session_state.get('last_3d_figure')

    if fig is not None:
        st.plotly_chart(
            fig,
            width='stretch',
            key=f"twin_3d_{fleet.id}",
        )
    else:
        st.info("📦 No packed items — awaiting cargo placement.")


def render_digital_twin_more(fleet: Fleet):
    """
    Render the "More" expander containing the Virtual Rear-CCTV view
    (deterministic render of THIS layout). Kept separate from the body so
    tri_view_panel.py can place this expander in its own row, aligned with
    the CCTV panel's "More" expander.
    """
    layout = fleet.packing_layout.get('layout', {})
    packed_items = layout.get('packed_items', [])
    if not packed_items:
        return
    # A fixed virtual camera mounted outside/near the rear loading opening
    # renders the packing plan as a 2D image — the digital "intended view"
    # a real rear-mounted CCTV would approximate. Works identically for the
    # live Dock 1 layout and the predetermined Docks 2-4 mock layouts.
    # Collapsed by default behind a "More" expander (same pattern as the
    # CCTV panel in tri_view_panel.py) so the twin view stays compact for
    # every dock; the backend render/Gemini pipeline is untouched.
    with st.expander("More", expanded=False):
            try:
                from services.virtual_camera import render_virtual_cctv_for_fleet
                vpath = render_virtual_cctv_for_fleet(fleet)
                if vpath:
                    st.image(vpath, width='stretch')
                    st.caption(
                        "📹 **Virtual Rear-CCTV View** — fixed camera outside "
                        "the rear loading opening, looking in (digital intended "
                        "view) • red strip = rear-loading-door zone • cyan "
                        "'DIGITAL TWIN' watermark badge marks this as a "
                        "simulated view, not real CCTV • reproducible PNG artifact"
                    )
                else:
                    st.caption("Virtual rear-CCTV view unavailable for this layout.")
            except Exception as exc:  # never break the Digital Twin panel
                st.caption(f"Virtual rear-CCTV view unavailable: {exc}")