"""
components/digital_twin.py
===========================
Digital Twin (3D Bin Packing Plan) component.

  - Renders the generated 3D Bin Packing canvas/layout (the "Gold Standard"
    created from View 1) as an interactive 3D scene.
  - Reuses render_packing_visual logic from app.py.
"""

import streamlit as st
import plotly.graph_objects as go
from typing import List, Tuple, Dict, Any, Optional
from state.fleet_state import Fleet


def _f(value, default=0.0) -> float:
    """Coerce py3dbp numerics (often decimal.Decimal) to float safely."""
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def render_digital_twin(fleet: Fleet):
    """
    Render the Digital Twin 3D visualization of the optimal packing plan.

    Parameters
    ----------
    fleet : Fleet
        The fleet whose packing_layout will be rendered.
    """
    layout = fleet.packing_layout.get('layout', {})
    packed_items = layout.get('packed_items', [])

    WHD = layout.get('WHD', (1203, 235, 238))
    # Convert cm to meters for display (values may be decimal.Decimal)
    truck_w = _f(WHD[0]) / 100.0
    truck_h = _f(WHD[1]) / 100.0
    truck_d = _f(WHD[2]) / 100.0

    st.subheader("Digital Twin — 3D Packing Plan (Gold Standard)")
    st.caption("Optimal layout generated by the Loading Planner (View 1)")

    # Summary metrics
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Fill Rate", f"{fleet.fill_percentage:.1f}%")
    with col2:
        st.metric("Packed Items", f"{len(packed_items)}")
    with col3:
        total_weight = sum(_f(p.get('weight', 0)) for p in packed_items)
        st.metric("Total Weight", f"{total_weight:.0f} kg")
    with col4:
        unfitted = layout.get('unfitted_items', [])
        st.metric("Unfitted", f"{len(unfitted)}")

    # Build 3D scene
    fig = _build_3d_scene(packed_items, truck_w, truck_h, truck_d)

    st.plotly_chart(
        fig,
        width='stretch',
        key=f"twin_3d_{fleet.id}",
    )

    # Display packed item details
    if packed_items:
        with st.expander("Packed Items Details"):
            for item in packed_items:
                pos = [_f(v) for v in item.get('position', [0, 0, 0])]
                dims = [_f(v) for v in item.get('dimensions', [0, 0, 0])]
                st.markdown(
                    f"**{item['part_number']}** — "
                    f"Pos: ({pos[0]:.0f}, {pos[1]:.0f}, {pos[2]:.0f}) cm | "
                    f"Dims: ({dims[0]:.0f}, {dims[1]:.0f}, {dims[2]:.0f}) cm | "
                    f"Weight: {item.get('weight', 0):.0f} kg"
                )


def _build_3d_scene(
    packed_items: List[Dict],
    truck_w: float,
    truck_h: float,
    truck_d: float,
) -> go.Figure:
    """
    Build a Plotly 3D scene showing the truck container and packed items.
    """
    fig = go.Figure()

    # Draw the truck container as a wireframe
    _add_truck_outline(fig, truck_w, truck_h, truck_d)

    # Draw each packed item
    palette = [
        "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728",
        "#9467bd", "#8c564b", "#e377c2", "#17becf",
    ]

    for i, item in enumerate(packed_items):
        pos = [_f(v) for v in item.get('position', [0, 0, 0])]
        dims = [_f(v) for v in item.get('dimensions', [10, 10, 10])]
        color = item.get('color', None) or palette[i % len(palette)]

        # Convert cm to meters
        x, y, z = pos[0] / 100, pos[1] / 100, pos[2] / 100
        w, h, d = dims[0] / 100, dims[1] / 100, dims[2] / 100

        _add_cuboid(fig, x, y, z, w, h, d, color, item.get('part_number', f'Item {i}'))

    fig.update_layout(
        scene=dict(
            xaxis=dict(visible=False, range=[0, truck_w + 0.1]),
            yaxis=dict(visible=False, range=[0, truck_h + 0.1]),
            zaxis=dict(visible=False, range=[0, truck_d + 0.1]),
            aspectmode='manual',
            aspectratio=dict(x=truck_w, y=truck_h, z=truck_d),
            camera=dict(
                eye=dict(x=-1.8, y=1.6, z=1.8)
            ),
        ),
        margin=dict(l=0, r=0, t=40, b=0),
        height=500,
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)',
    )

    return fig


def _add_truck_outline(fig, w, h, d):
    """Add the truck container as a wireframe outline."""
    # 8 corners of the truck
    corners = [
        (0, 0, 0), (w, 0, 0), (w, h, 0), (0, h, 0),
        (0, 0, d), (w, 0, d), (w, h, d), (0, h, d),
    ]
    edges = [
        (0,1), (1,2), (2,3), (3,0),  # bottom
        (4,5), (5,6), (6,7), (7,4),  # top
        (0,4), (1,5), (2,6), (3,7),  # verticals
    ]

    for i, j in edges:
        c1, c2 = corners[i], corners[j]
        fig.add_trace(go.Scatter3d(
            x=[c1[0], c2[0]],
            y=[c1[1], c2[1]],
            z=[c1[2], c2[2]],
            mode='lines',
            line=dict(color='#64748b', width=3),
            name='Container',
            showlegend=False,
        ))


def _add_cuboid(fig, x, y, z, w, h, d, color, label):
    """Add a 3D cuboid (cargo item) to the scene."""
    # 8 corners
    corners = [
        (x,       y,       z),
        (x + w,   y,       z),
        (x + w,   y + h,   z),
        (x,       y + h,   z),
        (x,       y,       z + d),
        (x + w,   y,       z + d),
        (x + w,   y + h,   z + d),
        (x,       y + h,   z + d),
    ]
    edges = [
        (0,1), (1,2), (2,3), (3,0),
        (4,5), (5,6), (6,7), (7,4),
        (0,4), (1,5), (2,6), (3,7),
    ]

    for i, j in edges:
        c1, c2 = corners[i], corners[j]
        fig.add_trace(go.Scatter3d(
            x=[c1[0], c2[0]],
            y=[c1[1], c2[1]],
            z=[c1[2], c2[2]],
            mode='lines',
            line=dict(color=color, width=4),
            name=label,
            showlegend=False,
        ))

    # Add center point for hover info
    fig.add_trace(go.Scatter3d(
        x=[x + w/2],
        y=[y + h/2],
        z=[z + d/2],
        mode='markers+text',
        marker=dict(size=1, color='rgba(0,0,0,0)'),
        text=label,
        textposition="top center",
        name=label,
        showlegend=False,
        hovertemplate=f"<b>{label}</b><br>X:{x:.1f} Y:{y:.1f} Z:{z:.1f}<br>W:{w:.1f} H:{h:.1f} D:{d:.1f}<extra></extra>",
    ))
